git:
  submodules: false
  quiet: true
  depth: 3

language: php

php:
  - '7.0'
  - '7.1'
  - '7.2'

env:
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=^3.0

before_script:
  - composer require --prefer-dist --no-interaction --no-suggest --no-progress symfony/config:${SYMFONY_VERSION} symfony/console:${SYMFONY_VERSION} symfony/dependency-injection:${SYMFONY_VERSION} symfony/event-dispatcher:${SYMFONY_VERSION} symfony/http-kernel:${SYMFONY_VERSION} symfony/yaml:${SYMFONY_VERSION}

cache:
  directories:
    - $HOME/.composer/cache