git:
  submodules: false
  quiet: true
  depth: 3

language: php

php:
  - '7.0'
  - '7.1'
  - '7.2'

env:
  - SYMFONY_VERSION=2.8.* COVERAGE
  - SYMFONY_VERSION=^3.0 COVERAGE

before_script:
  - |
    if [[ "$COVERAGE" != "1" ]]; then
      phpenv config-rm ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini || echo "xdebug is not installed"
    fi
  - composer require --prefer-dist --no-interaction --no-suggest --no-progress symfony/config:${SYMFONY_VERSION} symfony/console:${SYMFONY_VERSION} symfony/dependency-injection:${SYMFONY_VERSION} symfony/event-dispatcher:${SYMFONY_VERSION} symfony/http-kernel:${SYMFONY_VERSION} symfony/yaml:${SYMFONY_VERSION}
  - mkdir -p build/logs

after_success:
  - travis_retry php vendor/bin/php-coveralls -v

cache:
  directories:
    - $HOME/.composer/cache