language: php

php:
  - '5.4'
  - '5.6'
  - '7.0.8'
  - '7.2.34'

env:
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=^3.0

before_script:
  - composer require symfony/config:${SYMFONY_VERSION} symfony/console:${SYMFONY_VERSION} symfony/dependency-injection:${SYMFONY_VERSION} symfony/event-dispatcher:${SYMFONY_VERSION} symfony/http-kernel:${SYMFONY_VERSION} symfony/yaml:${SYMFONY_VERSION}