@startuml

!include config/plantuml.cfg

rectangle "ProjectCollection" {
(Project) as (PR)
    rectangle "PlanCollection 1" {
        (Plan 1) as (PL1)
        (Plan 2) as (PL2)
        (Plan 3) as (PL3)
    }
(Project2) as (PR2)
    rectangle "PlanCollection 2" {
        (Plan 4) as (PL4)
    }
}

child(PR, PL1)
child(PR, PL2)
child(PR, PL3)
child(PR2, PL4)

@enduml