flowchart LR
    PR1(["Project [0]"])
    PL1(["Project [0] Plan [0]"])
    PL2(["Project [0] Plan [1]"])
    PL3(["Project [0] Plan [2]"])
    PL4(["Project [0] Plan [3]"])

    PR2(["Project [1]"])
    PL5(["Project [1] Plan [0]"])
    PL6(["Project [1] Plan [1]"])

    PR1 --> PL1
    PR1 --> PL2
    PR1 --> PL3
    PR1 --> PL4

    PR2 --> PL5
    PR2 --> PL6
