@startuml

left to right direction

!include config/plantuml.cfg

(Project) as (PR)

rectangle PlanCollection {
    (Plan 1) as (PL1)
    (Plan 2) as (PL2)
    (Plan 3) as (PL3)
}

child(PR, PL1)
child(PR, PL2)
child(PR, PL3)

@enduml