@startuml

left to right direction

!include config/plantuml.cfg

rectangle "Project Collection" {
(Project) as (PR)
    rectangle "Plan Collection 1" {
        (Plan 1) as (PL1)
            rectangle "Plan Branch Collection 1" {
                (Plan Branch 1) as (PB1)
                (Plan Branch 2) as (PB2)
            }
        (Plan 2) as (PL2)
        (Plan 3) as (PL3)
            rectangle "Plan Branch Collection 2" {
                (Plan Branch 3) as (PB3)
                (Plan Branch 4) as (PB4)
            }
    }
(Project2) as (PR2)
    rectangle "Plan Collection 2" {
        (Plan 4) as (PL4)
            rectangle "Plan Branch Collection 3" {
                (Plan Branch 5) as (PB5)
            }
    }
}

child(PR, PL1)
child(PL1, PB1)
child(PL1, PB2)
child(PR, PL2)
child(PR, PL3)
child(PL3, PB3)
child(PL3, PB4)
child(PR2, PL4)
child(PL4, PB5)

@enduml